// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfPkgQb70hEebMY0iiUhNtLRMMO96e-x0',
    appId: '1:247165886071:web:361b1bd5fdcc61259e3072',
    messagingSenderId: '247165886071',
    projectId: 'fccthegurukul-2',
    authDomain: 'fccthegurukul-2.firebaseapp.com',
    databaseURL: 'https://fccthegurukul-2-default-rtdb.firebaseio.com',
    storageBucket: 'fccthegurukul-2.firebasestorage.app',
    measurementId: 'G-GWREQE5V5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxdpT0ZXRtCUnwscQhnGir8pxOwLEiWsY',
    appId: '1:247165886071:android:842a15dbca60096c9e3072',
    messagingSenderId: '247165886071',
    projectId: 'fccthegurukul-2',
    databaseURL: 'https://fccthegurukul-2-default-rtdb.firebaseio.com',
    storageBucket: 'fccthegurukul-2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfPkgQb70hEebMY0iiUhNtLRMMO96e-x0',
    appId: '1:247165886071:web:0c7c2c41a340b3179e3072',
    messagingSenderId: '247165886071',
    projectId: 'fccthegurukul-2',
    authDomain: 'fccthegurukul-2.firebaseapp.com',
    databaseURL: 'https://fccthegurukul-2-default-rtdb.firebaseio.com',
    storageBucket: 'fccthegurukul-2.firebasestorage.app',
    measurementId: 'G-B3S5ZQ23N8',
  );
}
